config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  
  root to: 'visitors#index'
  
  get '/dashboard', to: 'home#dashboard', as: :dashboard

  resources :goals, except: [:index]
  resources :activities, except: [:show]
  resources :users, only: [:edit, :update]
  resources :milestones, except: [:show]

  get '/help', to: 'home#help', as: :help
  get '/site-wide-stats', to: 'home#site_wide_stats', as: :site_wide_stats

  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: :unsubscribe

  get '/users/:id/milestones/:milestone_id', to: 'users#share_milestone', as: :share_milestone
  get '/users/:id/share/:achievement', to: 'users#share_achievement', as: :share_achievement

  get '/activities/trigger_import', to: 'activities#trigger_import', as: 'trigger_import'
end

app/models/milestone.rb
# == Schema Information
#
# Table name: milestones
#
#  id            :bigint           not null, primary key
#  metric        :string
#  threshold     :decimal(, )
#  created_by_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Milestone < ApplicationRecord
  belongs_to :created_by, class_name: 'User', foreign_key: 'created_by_id', optional: true
  has_and_belongs_to_many :users

  validates_presence_of :threshold, :metric
  
  before_save :unit_conversion
  after_save :trigger_update_milestones_job

  has_one_attached :badge

  METRICS = %w(distance vertical_gain combined carbon)

  # before save callback that ensures all `totals` are saved in miles
  # or feet
  # assumes incoming units are the created_by user's
  def unit_conversion
    if created_by.try(:metric_system?)
      old_threshold = self.threshold
      if metric == 'distance'
        self.threshold = Goal.kms_to_miles(old_threshold)
      elsif metric == 'vertical_gain'
        self.threshold = Goal.meters_to_feet(old_threshold)
      end
    end
  end

  def metric_needs_conversion?
    if ['distance', 'vertical_gain'].include? metric
      true
    else
      false
    end
  end

  def trigger_update_milestones_job
    UpdateMilestonesJob.perform_later
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  
  def index
    @milestones = @milestones.order('threshold asc')
  end

  def create
    @milestone.created_by = current_user

    if @milestone.save
      flash[:notice] = 'Milestone created'
      redirect_to milestones_path
    else
      flash[:error] = 'There was an error creating the milestone'
      render 'new'
    end
  end

  def update
    if @milestone.update(milestone_params)
      flash[:notice] = 'Milestone updated'
      redirect_to milestones_path
    else
      flash[:error] = 'There was an error updating the milestone'
      render 'edit'
    end
  end

  def new
  end

  def edit
  end

  def destroy
    @milestone.destroy!
    flash[:notice] = 'Removed milestone'
    redirect_to milestones_path
  end

  private

  def milestone_params
    params[:milestone][:threshold].gsub!(',', '')
    params.require(:milestone).permit(:threshold, :metric, :badge, :tagline)
  end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
  def friendly_display_of_threshold(milestone, user)
    if milestone.metric_needs_conversion?
      label = Goal.metric_label(milestone.metric, user.measurement_system)
      if user.imperial_system?
        number = milestone.threshold.to_i
      else
        if milestone.metric == 'distance'
          number = Goal.miles_to_kms(milestone.threshold)
        elsif milestone.metric = 'vertical_gain'
          number = Goal.feet_to_meters(milestone.threshold)
        end
        number.round
      end

      return "#{number} #{label}"
    elsif milestone.metric == 'carbon'
      return "#{milestone.threshold} tons"
    elsif milestone.metric == 'combined'
      return "#{milestone.threshold} combined"
    else
      return milestone.threshold
    end
  end

  def exact_converted_display_of_threshold(milestone, user)
    if milestone.metric_needs_conversion?
      if user.imperial_system?
        number = milestone.threshold.to_i
      else
        if milestone.metric == 'distance'
          number = Goal.miles_to_kms(milestone.threshold)
        elsif milestone.metric = 'vertical_gain'
          number = Goal.feet_to_meters(milestone.threshold)
        end
      end
      return number
    else
      return milestone.threshold
    end
  end

  def milestone_achievement_verb(milestone)
    milestone.metric == 'distance' ? "traveled" : "gained"
  end

  def milestone_metrics_select_values(user)
    Milestone::METRICS.map do |metric|
      if metric == 'distance' || metric == 'vertical_gain'
        [Goal::METRICS_LABELS[metric][user.measurement_system], metric]
      elsif metric == 'carbon'
        ["tons of carbon", metric]
      else
        [metric, metric]
      end
    end
  end
end

app/views/milestones/_badge.html.haml
.card.milestone-badge.d-flex.flex-column
  = image_tag milestone.badge if milestone.badge.attached?
  %span.badge.badge-primary.badge-pill
    - if milestone.tagline.present?
      = milestone.tagline
    - else
      = friendly_display_of_threshold(milestone, current_user)
  - if current_user.milestones.include? milestone
    = link_to "Share", share_milestone_path(id: current_user.id, milestone_id: milestone.id), class: 'py-2'

app/views/milestones/_form.html.haml
= form_for @milestone do |f|
  - if @milestone.errors.any?
    #error_explanation.alert.alert-danger
      %h2
        #{pluralize(@milestone.errors.count, 'error')} prohibited this milestone from being created:
      %ul
        - @milestone.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    .form-row
      .col-md-10
        Reward users for reaching 
        = f.text_field :threshold, placeholder: '1000', value: exact_converted_display_of_threshold(@milestone, current_user)
        = f.select :metric, milestone_metrics_select_values(current_user)
  .form-group
    .form-row
      .col-md-10
        = f.label :tagline
        = f.text_field :tagline, placeholder: "Peak Pusher"
  .form-group.d-flex
    %div
      = f.label :badge
      = f.file_field :badge
    - if @milestone.badge.attached?
      = image_tag @milestone.badge, class: 'milestone-badge'

  = f.submit 'Submit', class: 'btn btn-primary btn-block'

app/views/milestones/edit.html.haml
.card.mb-3
  .card-header Modify a milestone for users
  .card-body
    .alert.alert-info Modifying an existing milestone will result in it being removed from users that no longer qualify
    = render 'milestones/form'

app/views/milestones/index.html.haml
.row
  .col-12
    - if current_user.admin?
      = link_to 'Create a New Milestone', new_milestone_path, class: 'float-md-right btn btn-success'
    %h1 Milestones
    .card.mb-3
      .card-header What are milestones?
      .card-body
        %p
          When you upload activities that push you over a threshold, you'll earn a badge for completing the
          milestone. You can also win prizes from BAR-U-EAT, cash that will go towards
          environmental non-profits, and more!
.card.mb-3
  .card-header Milestones
  .card-body
    .table-responsive
      %table.table.table-bordered#milestoneTable
        %thead
          %th Badge
          %th Number of Users Achieved
          %th Achieved?
          - if current_user.admin?
            %th
        %tbody
          - @milestones.each do |milestone|
            %tr{ class: "milestone-#{milestone.id}" }
              %td= render partial: "milestones/badge", locals: { milestone: milestone }
              %td= milestone.users.count
              %td
                - if current_user.milestones.include?(milestone)
                  %svg{ xmlns: "http://www.w3.org/2000/svg", width: "16", height: "16", fill: "currentColor", class: "bi bi-check2-square", viewBox: "0 0 16 16" }
                    %path{ d: "M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z" }
                    %path{ d: "m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z" }
              - if current_user.admin?
                %td
                  = link_to 'Edit', edit_milestone_path(milestone), class: 'btn btn-sm btn-warning'
                  = link_to 'Delete', milestone_path(milestone), class: 'btn btn-sm btn-danger', method: :delete, confirm: "Are you sure?"

app/views/milestones/new.html.haml
.card.mb-3
  .card-header Create a milestone for users
  .card-body
    = render 'milestones/form'