config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  
  root to: 'visitors#index'
  
  get '/dashboard', to: 'home#dashboard', as: :dashboard

  resources :goals, except: [:index]
  resources :activities, except: [:show]
  resources :users, only: [:edit, :update]
  resources :milestones, except: [:show]

  get '/help', to: 'home#help', as: :help
  get '/site-wide-stats', to: 'home#site_wide_stats', as: :site_wide_stats

  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: :unsubscribe

  get '/users/:id/milestones/:milestone_id', to: 'users#share_milestone', as: :share_milestone
  get '/users/:id/share/:achievement', to: 'users#share_achievement', as: :share_achievement

  get '/activities/trigger_import', to: 'activities#trigger_import', as: 'trigger_import'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def dashboard
  end

  def help
  end

  def site_wide_stats
    # stats are in imperial system by default since that's what's in the db
    @summary = {
      users: User.count,
      vertical_gain_goal: Goal.where(metric: :vertical_gain).sum(:total),
      distance_goal: Goal.where(metric: :distance).sum(:total),
      vertical_gain_sum: Activity.sum(:vertical_gain),
      distance_sum: Activity.sum(:distance)
    }
    if current_user.metric_system?
      @summary[:vertical_gain_goal] = Goal.feet_to_meters(@summary[:vertical_gain_goal])
      @summary[:vertical_gain_sum] = Goal.feet_to_meters(@summary[:vertical_gain_sum])
      @summary[:distance_goal] = Goal.miles_to_kms(@summary[:distance_goal])
      @summary[:distance_sum] = Goal.miles_to_kms(@summary[:distance_sum])
    end

    @leaderboard = User.top_three_users_this_month
  end
end

app/views/home/_leaderboard.html.haml
.card
  .card-header Monthly Leaderboard
  .card-body
    - if @leaderboard[:most_distance].nil? || @leaderboard[:most_vert].nil? || @leaderboard[:most_combined].nil?
      %h5 There aren't any leaders yet. Get out there!
    - else
      .row
        .col-12.col-md-4
          .card.text-center
            .card-header Most Distance
            .card-body.user-avatar
              - if @leaderboard[:most_distance].avatar.attached?
                = image_tag @leaderboard[:most_distance].avatar
              %h5= @leaderboard[:most_distance].name
              %h6= display_distance(@leaderboard[:most_distance].distance)
        .col-12.col-md-4
          .card.text-center
            .card-header Most Elevation
            .card-body.user-avatar
              - if @leaderboard[:most_vert].avatar.attached?
                = image_tag @leaderboard[:most_vert].avatar
              %h5= @leaderboard[:most_vert].name
              %h6= display_vert(@leaderboard[:most_vert].vert)
        .col-12.col-md-4
          .card.text-center
            .card-header Most Combined
            .card-body.user-avatar
              - if @leaderboard[:most_combined].avatar.attached?
                = image_tag @leaderboard[:most_combined].avatar
              %h5= @leaderboard[:most_combined].name
              %h6
                #{display_distance(@leaderboard[:most_combined].distance)} + #{display_vert(@leaderboard[:most_combined].vert)}

app/views/home/_site_wide_stats.html.haml
%section
  = render partial: "home/leaderboard"
  .card
    .card-header #CarFreeChallenge Participants
    .card-body.text-center.p-0
      %h1
        .badge.text-primary= @summary[:users]
    %hr.my-0
    .card-header
      Total Carbon Offset
    .card-body.text-center
      %h1
        .badge.text-primary= emissions_given_distance(@summary[:distance_sum])
    %hr.my-0
    .card-header Total Vertical Gain
    .card-body.text-center.p-0
      %h1
        .badge.text-primary= display_vert(@summary[:vertical_gain_sum])
    %hr.my-0
    .card-header Total Distance
    .card-body.text-center.p-0
      %h1
        .badge.text-primary= display_distance(@summary[:distance_sum])

app/views/home/dashboard.html.haml
- if current_user.goals.empty? and current_user.activities.empty?
  %section.mb-4
    .row
      .col-lg-12
        .card.mb-3
          .card-header Getting Started
          .card-body
            %ol
              %li
                Set a goal for car-free vertical gain or distance by clicking
                = link_to "+ Set a Goal", new_goal_path, class: 'btn btn-info btn-sm'
              %li
                - if current_user.is_strava_user?
                  Log activities on Strava with the text "#carfreechallenge" or "#cfc" in the title
                - else
                  = link_to "Log activities", activities_path
                  (or
                  = succeed ')' do
                    = link_to user_strava_omniauth_authorize_path do
                      = image_tag "btn_strava_connectwith_orange.svg", alt: "Connect with Strava"
              %li
                Share your goals  with your friends using the "Share" button next to your goal
              %li
                Share your adventures on
                = link_to 'Instagram', 'https://www.instagram.com/carfreechallenge/'
                and
                = link_to 'Facebook', 'https://www.facebook.com/carfreechallenge/'
                with the hashtag #CarFreeChallenge

%section.mb-4
  .row.mb-4
    .col-lg-4
      .card
        .card-header= current_user.name
        .card-body.user-avatar.d-flex.align-items-center
          - if current_user.avatar.attached?
            = image_tag current_user.avatar 
    .col-lg-8
      .card
        .card-header Activities Logged
        .card-body.text-center
          %h1
            .badge.text-primary= current_user.activities.count
      .card
        .card-header
          Total Carbon Offset
        .card-body.text-center
          %h1
            .badge.text-primary= emissions_given_distance(current_user.activities.sum(:distance))
      .card
        .card-header
          Total Vertical Gain
        .card-body.text-center
          %h1
            .badge.text-primary= display_vert(current_user.activities.sum(:vertical_gain))
      .card
        .card-header
          Total Distance
        .card-body.text-center
          %h1
            .badge.text-primary= display_distance(current_user.activities.sum(:distance))
  .row.mb-4
    .col-lg-12
      .card
        .card-header
          Your Goals
          = link_to '+ Set a Goal', new_goal_path, class: 'btn btn-info float-right'
        - current_user.goals.each do |g|
          .card-body{ class: "goal goal-#{g.id}" }
            .row
              .col-lg-8
                %p
                  %strong= g.converted_total
                  car-free
                  %strong= g.metric_label
                  - if g.start_date.present?
                    between
                    %strong= g.start_date.strftime("%b %d, %Y")
                    and
                  - else
                    by
                  %strong= g.end_date.try(:strftime,"%b %d, %Y")
              .col-lg-4
                .btn-group
                  = link_to 'Share', goal_path(g), class: 'btn btn-success btn-sm'
                  = link_to 'Edit', edit_goal_path(g), class: 'btn btn-warning btn-sm'
                  = link_to 'Delete', goal_path(g), class: 'btn btn-danger btn-sm', method: :delete
            .row
              .col-sm-12.progress-bar-container
                .progress
                  = progress_bar(g)
  .row
    .col-lg-12
      .card
        .card-header Badges Earned
        .card-body.row
          - current_user.achievements.each do |a|
            .col-lg-3
              .card.milestone-badge.d-flex.flex-column.achievement
                = image_tag "achievements/#{a.to_s}.png", alt: a.to_s.titlecase
                %span.badge.badge-primary.badge-pill= a.to_s.titlecase
                = link_to "Share", share_achievement_path(id: current_user.id, achievement: a.to_s), class: 'py-2'
          - current_user.milestones.each do |m|
            .col-lg-3
              = render partial: 'milestones/badge', locals: { milestone: m }

app/views/home/help.html.haml
%section
  .card.mb-3
    .card-header Issues or Suggestions?
    .card-body
      If you're running into an issue with the site, please email us
      with a description of the problem. 
%section
  .card.mb-3
    .card-header Want to Help?
    .card-body
      %p
        Share with your friends and don't forget to tag your activities on Strava! We greatly
        appreciate you promoting your activities and using the hashtag #CarFreeChallenge on
        all social platforms so we can continue to spread the word and achieve our mission of
        environmentally friendly activities, just beyond your front door!
%section
  = mail_to 'info@barueat.com', nil, class: 'btn btn-primary btn-block'

app/views/home/site_wide_stats.html.haml
= render "home/site_wide_stats"