config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  
  root to: 'visitors#index'
  
  get '/dashboard', to: 'home#dashboard', as: :dashboard

  resources :goals, except: [:index]
  resources :activities, except: [:show]
  resources :users, only: [:edit, :update]
  resources :milestones, except: [:show]

  get '/help', to: 'home#help', as: :help
  get '/site-wide-stats', to: 'home#site_wide_stats', as: :site_wide_stats

  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: :unsubscribe

  get '/users/:id/milestones/:milestone_id', to: 'users#share_milestone', as: :share_milestone
  get '/users/:id/share/:achievement', to: 'users#share_achievement', as: :share_achievement

  get '/activities/trigger_import', to: 'activities#trigger_import', as: 'trigger_import'
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id            :bigint           not null, primary key
#  distance      :decimal(, )
#  vertical_gain :decimal(, )
#  activity_date :datetime
#  sport         :string
#  user_id       :bigint
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  name          :string
#  external_id   :string
#  provider      :string
#

class Activity < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validate :metric_data_available
  validates :external_id, uniqueness: { scope: :provider }, if: :external_id?

  before_save :unit_conversion
  after_save :trigger_user_milestone_check

  STRAVA_UPDATEABLE_ATTRIBUTES = [:name, :sport, :activity_date, :distance, :vertical_gain]
  STRAVA_HASHTAG_MATCHERS = %w(#cfc #carfreechallenge #thecarfreechallenge)
  AFTER_EPOCH = "1659312000"
  PER_PAGE = 200

  # before save callback that ensures all `totals` are saved in miles
  # or feet
  def unit_conversion
    if user.metric_system?
      self.distance = Goal.kms_to_miles(distance) if distance.present?
      self.vertical_gain = Goal.meters_to_feet(vertical_gain) if vertical_gain.present?
    end
  end

  def converted_distance
    if distance?
      if user.imperial_system? or distance.blank?
        distance.try(:round, 2)
      else
        Goal.miles_to_kms(distance).round(2)
      end
    else
      nil
    end
  end

  def converted_vertical_gain
    if vertical_gain?
      if user.imperial_system? or vertical_gain.blank?
        vertical_gain.try(:round)
      else
        Goal.feet_to_meters(vertical_gain).round
      end
    else
      nil
    end
  end

  def self.update_or_create_from_strava(data)
    user = User.find_by(provider: 'strava', uid: data.athlete.id)

    activity = Activity.find_or_create_by(user: user, provider: 'strava', external_id: data.id)

    # strava provides distance and total_elevation_gain in meters,
    # so we need to ensure this works properly
    if user.present? and user.metric_system? # conversion happens automatically on save
      activity.distance = data.distance / 1000 # make kms instead of ms
      activity.vertical_gain = data.total_elevation_gain
    else
      activity.distance = Goal.kms_to_miles(data.distance / 1000)
      activity.vertical_gain = Goal.meters_to_feet(data.total_elevation_gain)
    end

    activity.name = data.name if data.name.present?
    activity.sport = data.type if data.type.present?
    activity.activity_date = data.start_date if data.start_date.present?

    activity.save!
    activity
  end

  def trigger_user_milestone_check
    user.update_milestones
  end

  private

  def metric_data_available
    if distance.blank? and vertical_gain.blank?
      errors.add(:base, "Specify at least one metric for your activity -- distance or vertical gain")
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.import_in_progress?
      flash[:notice] = "Importing can take a few minutes. Check back in a bit!"
    end
    @activities = current_user.activities
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    if @activity.save
      flash[:notice] = 'Thanks for logging your progress!'
      redirect_to activities_url
    else
      render 'new'
    end
  end

  def new
    @activity = Activity.new
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy! if @activity.user == current_user
    flash[:notice] = 'Activity deleted'
    redirect_to activities_path
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    if @activity.update activity_params
      flash[:notice] = "Activity updated"
      redirect_to activities_url
    else
      render 'edit'
    end
  end

  def trigger_import
    if current_user.is_strava_user?
      StravaImportJob.perform_later(current_user)
    end
    redirect_to activities_url
  end

  private

  def activity_params
    # if both metrics are blank, the activity is invalid, but if only one is blank, the other needs to be set to 0
    unless params[:activity][:distance].blank? && params[:activity][:vertical_gain].blank?
      [:distance, :vertical_gain].each do |metric|
        params[:activity][metric].gsub!(',','')
        params[:activity][metric] = 0 if params[:activity][metric].blank?
      end
    end

    params.require(:activity).permit(:distance, :vertical_gain, :activity_date, :sport, :name)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def display_distance(distance)
    if !current_user || current_user.imperial_system?
      number = distance
      measurement_system = "imperial_system"
    else
      number = Goal.miles_to_kms(distance)
      measurement_system = "metric_system"
    end

    return "#{number_with_delimiter number.round} #{Goal.metric_label('distance', measurement_system)}"
  end

  def display_vert(vert)
    if !current_user || current_user.imperial_system?
      number = vert
      measurement_system = "imperial_system"
    else
      number = Goal.feet_to_meters(vert)
      measurement_system = "metric_system"
    end

    return "#{number_with_delimiter number.round} #{Goal.metric_label('vertical_gain', measurement_system)}"
  end

  def emissions_given_distance(distance)
    tons = distance * 404 / 1000000
    "#{tons.round(2)} metric tons"
  end
end

app/views/activities/_form.html.haml
.row
  .col-12
    = form_for @activity do |f|
      - if @activity.errors.any?
        #error_explanation.alert.alert-danger
          %h2
            #{pluralize(@activity.errors.count, 'error')} prohibited this activity from being logged:
          %ul
            - @activity.errors.full_messages.each do |msg|
              %li= msg
      %h4 Required Stuff
      .form-group
        .form-row
          .col-md-4
            = f.text_field :distance, placeholder: '25', class: 'form-control',
              value: @activity.converted_distance
            = f.label :distance, Goal.metric_label('distance', current_user.measurement_system)
          .col-md-4
            = f.text_field :vertical_gain, placeholder: '1000', class: 'form-control',
              value: @activity.converted_vertical_gain
            = f.label :vertical_gain, Goal.metric_label('vertical_gain', current_user.measurement_system)
          .col-md-4
            %small.form-text.text-muted (both are allowed, but at least one is required)
      %hr
      %h4 Optional Fields
      .form-group
        .form-row
          .col-md-8
            = f.text_field :name, placeholder: '#carfreechallenge ski day out the back door!', class: 'form-control'
            = f.label :name, "Title"
        .form-row
          .col-md-4
            = f.date_field :activity_date, class: 'form-control'
            = f.label :activity_date
          .col-md-4
            = f.text_field :sport, class: 'form-control', placeholder: 'NordicSki'
            = f.label :sport
      = f.submit 'Submit', class: 'btn btn-primary btn-block'

app/views/activities/create.html.haml
%h1 Activities#create
%p Find me in app/views/activities/create.html.haml

app/views/activities/edit.html.haml
%h1 Edit Activity
- if @activity.provider.present?
  .alert.alert-info
    Editing your activity here will be overwritten the next time your activities are
    imported from Strava (unless you've removed the activity there). Consider editing
    the activity there if you want the changes to persist.
= render 'activities/form'

app/views/activities/index.html.haml
.row
  .col-12
    = link_to '+ Log an activity', new_activity_path, class: 'float-md-right btn btn-success'
    - if current_user.is_strava_user?
      #import_button.float-md-right
        = link_to "Import Activities From Strava", trigger_import_path,
          class: "btn btn-strava #{current_user.import_in_progress? ? 'importing disabled' : '' }"
    %h1 Log Your Progress
    - if current_user.is_strava_user?
      .card.mb-3
        .card-header How to Use #carfreechallenge With Strava
        .card-body
          %p
            It's really easy to log activities and progress since you already use Strava.
            Just add the hash tag
            %strong #carfreechallenge
            or
            %strong #cfc
            to the title of any applicable activities on Strava and they'll show up here
            and count towards your goals.
          %p
            When you login here, we automatically send a request to Strava to retrieve activities.
            You can also manually import by clicking the button above -- that will
            enqueue a background process to import your activities. You'll have to refresh to see them.
.card.mb-3
  .card-header Progress Log
  .card-body
    .table-responsive
      %table.table.table-bordered#activityTable
        %thead
          %th Activity Date
          %th Title
          %th Sport
          %th= Goal.metric_label('distance', current_user.measurement_system).titlecase
          %th= Goal.metric_label('vertical_gain', current_user.measurement_system).titlecase
          %th
        %tbody
          - @activities.each do |act|
            %tr{ class: "activity-#{act.id}" }
              %td= act.activity_date.try(:strftime,"%m-%d-%Y") || act.created_at.strftime("%m-%d-%Y")
              %td
                = act.name
                - if act.provider == "strava"
                  %strong.text-small
                    = surround '(', ')' do
                      = link_to "View on Strava", "https://www.strava.com/activities/#{act.external_id}"
              %td= act.sport
              %td= act.converted_distance
              %td= act.converted_vertical_gain
              %td
                = link_to 'Edit', edit_activity_path(act),
                  class: "btn btn-warning btn-sm edit-activity-#{act.id}"
                - if act.provider.present?
                  - confirm_message = "You can delete Strava activities here, but they'll |
                      be reimported unless you remove the #carfreechallenge hashtag on Strava" |
                - else
                  - confirm_message = "Are you sure?"
                = link_to 'Delete', activity_path(act), method: :delete,
                  class: "btn btn-danger delete-activity-#{act.id} btn-sm",
                  data: { confirm: confirm_message }

app/views/activities/new.html.haml
%h1 + Log Progress
.card.card-block.bg-light
  .card-body
    This isn't meant to be an activity tracker app. You can log every
    activity here (but if you're doing that, I'd recommend just signing up for
    = link_to 'Strava', 'http://www.strava.com'
    instead), or you can keep track elsewhere and just log vertical gain and/or distance
    here as often as you want your progress to update. You don't need a one-to-one correlation
    between activities and "progress", it's just for tracking your effort towards your goal.

%hr

= render 'activities/form'