config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  
  root to: 'visitors#index'
  
  get '/dashboard', to: 'home#dashboard', as: :dashboard

  resources :goals, except: [:index]
  resources :activities, except: [:show]
  resources :users, only: [:edit, :update]
  resources :milestones, except: [:show]

  get '/help', to: 'home#help', as: :help
  get '/site-wide-stats', to: 'home#site_wide_stats', as: :site_wide_stats

  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: :unsubscribe

  get '/users/:id/milestones/:milestone_id', to: 'users#share_milestone', as: :share_milestone
  get '/users/:id/share/:achievement', to: 'users#share_achievement', as: :share_achievement

  get '/activities/trigger_import', to: 'activities#trigger_import', as: 'trigger_import'
end

app/views/layouts/_app_navigation.html.haml
- if user_signed_in?
  %ul.navbar-nav.navbar-sidenav.bg-primary
    %li.nav-item{ class: (action_name == 'dashboard' ? 'active' : '') }
      = link_to 'Dashboard', dashboard_path, class: 'nav-link'
    %li.nav-item{ class: (controller_name == 'activities' ? 'active' : '') }
      = link_to 'Log Your Progress', activities_path, class: 'nav-link'
    %li.nav-item{ class: (action_name == 'site_wide_stats' ? 'active' : '') }
      = link_to 'Site-wide Stats', site_wide_stats_path, class: 'nav-link'
    %li.nav-item
      = link_to 'Browse Milestones', milestones_path, class: 'nav-link'
    %li.nav-item{ class: (action_name == 'help' ? 'active' : '') }
      = link_to 'Help', help_path, class: 'nav-link'
    %li.nav-item#appSocialLinks
      = render 'layouts/social_links'
      = image_tag "api_logo_cptblWith_strava_horiz_white.svg", alt: "Compatible with Strava", class: 'cptbl-with-strava-image'

app/views/layouts/_footer.html.haml
%footer.sticky-footer
  .container
    .text-center
      %small
        Created by
        = link_to 'Nick Gottlieb', 'http://www.nicholasgottlieb.com'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav#mainNav.navbar.navbar-dark.bg-primary.fixed-top.navbar-expand-lg
  = link_to root_path, class: 'navbar-brand' do
    = image_tag 'cfc-logo-white.png', alt: '#CarFreeChallenge'
  %button.navbar-toggler.navbar-toggler-right{ type: "button", data: { toggle: "collapse", target: "#navbarResponsive" },
    aria: { expanded: "false", label: "Toggle navigation", controls: 'navbarResponsive' }}
    %span.navbar-toggler-icon
  #navbarResponsive.navbar-collapse.collapse
    = render 'layouts/app_navigation'
    = render 'layouts/user_navigation'

app/views/layouts/_social_links.html.haml
.social-menu-container
  %ul.social-menu
    %li
      = link_to 'https://www.instagram.com/barueat/' do
        %svg#icon-instagram{ viewBox: "0 0 16 16", width: "100%", height: "100%" }
          %path{ d: "M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" }
    %li
      = link_to 'https://www.facebook.com/barueat/' do
        %svg#icon-facebook{ viewBox: "0 0 16 16", width: "100%", height: "100%" }
          %path{ d: "M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" }
    %li
      = link_to 'https://www.strava.com/clubs/THE-BARUEAT-COLLECTIVE' do
        %svg#icon-strava{ viewBox: "0 0 16 16", width: "100%", height: "100%" }
          %path{ d: "M6.731 0 2 9.125h2.788L6.73 5.497l1.93 3.628h2.766L6.731 0zm4.694 9.125-1.372 2.756L8.66 9.125H6.547L10.053 16l3.484-6.875h-2.112z" }

app/views/layouts/_user_navigation.html.haml
%ul.navbar-nav.ml-auto.user-nav
  - if user_signed_in?
    %li.nav-item= link_to "Account", edit_user_path(current_user), class: 'nav-link'
    %li.nav-item= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link'
  - else
    %li.nav-item= link_to "Login", new_user_session_path, class: "nav-link"
    %li.nav-item= link_to "Sign up", new_user_registration_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'The Car Free Challenge'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'The Car Free Challenge'}"}
    %meta{ property: 'og:title', content: 'Take the #carfreechallenge' }
    %meta{ property: 'og:description', content: "Pledge to minimize your driving for outdoor recreation by setting a goal for car free adventures!" }
    %meta{ property: 'og:image', content: image_url('landing-pg-1.jpg') }
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body.fixed-nav.sticky-footer.bg-dark
    %header
      = render 'layouts/navigation'
    .content-wrapper
      %main{:role => "main"}
        = render 'layouts/messages'
        = yield
    = render 'layouts/footer'

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Car Free Challenge'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Car Free Challenge'}"}
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body.bg-dark
    .container
      = yield

app/views/layouts/visitors.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'The Car Free Challenge'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'The Car Free Challenge'}"}
    %meta{ property: 'og:title', content: 'Take the #carfreechallenge' }
    %meta{ property: 'og:description', content: "Pledge to minimize your driving for outdoor recreation by setting a goal for car free adventures!" }
    %meta{ property: 'og:image', content: image_url('landing-pg-1.jpg') }
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body.landing-page
    = yield